rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - jruby-9.2
before_install:
  - gem install bundler
install:
  - bundle install
  - bundle --gemfile=gemfiles/minitest5.gemfile
  - bundle --gemfile=gemfiles/minitest4.gemfile
  - bundle --gemfile=gemfiles/test_unit_gem.gemfile
script:
  - bundle exec rake tests
